Repository jqPlot/jqPlot, pull requests merged in 2018-09, with the labels that each got.

#115 jqplot.highlighter.js > Added 'auto' as an option to tooltipLocation
  src/plugins/jqplot.highlighter.js
Labels: enhancement

#137 Fix for IE drag/zoom error
  src/plugins/jqplot.cursor.js
Labels: bug

#138 Fix for data handling.
  src/jqplot.core.js
Labels: bug

#161 Legend properties now respect options set by user.
  src/jqplot.tableLegendRenderer.js
Labels: bug

#167 Fix zero or negative auto barWidth and allow minimum value
  src/plugins/jqplot.barRenderer.js
Labels: bug

#173 Create Code Of Conduct
  CODE_OF_CONDUCT.md
Labels: organisation
